# Generated by Django 4.2.3 on 2023-07-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='entry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='exit_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='vacation_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
